parameters:
  product_subscriber.class: Heystack\Subsystem\Products\Product\Subscriber
  product_input_processor.class: Heystack\Subsystem\Products\Product\Input\Processor
  product_output_processor.class: Heystack\Subsystem\Products\Product\Output\Processor

  productholder_subscriber.class: Heystack\Subsystem\Products\ProductHolder\Subscriber

  productholder.class: Heystack\Subsystem\Products\ProductHolder\ProductHolder

  product.class: Product


services:

  product_subscriber:
    class: %product_subscriber.class%

  productholder_subscriber:
    class: %productholder_subscriber.class%

  event_dispatcher:
    calls: 
      - [ addSubscriber, [ @product_subscriber ] ]
      - [ addSubscriber, [ @productholder_subscriber ] ]

  product_input_processor:
    class: %product_input_processor.class%
    arguments: [%product.class%, @state, @event_dispatcher, @productholder]
    
  product_output_processor:
    class: %product_output_processor.class%
    arguments: [%product.class%, @state, @productholder]

  productholder:
    class: %productholder.class%
    arguments: [ @state, @event_dispatcher ]
    calls:
      - [ restoreState ]

  input_processor_handler:
    calls:
      - [ addProcessor, [ @product_input_processor ] ]

  output_processor_handler:
    calls:
      - [ addProcessor, [ @product_output_processor ] ]

