parameters:
  purchasable_input_processor.class: Heystack\Purchasable\Purchasable\Input\Processor
  purchasable_output_processor.class: Heystack\Purchasable\Purchasable\Output\Processor
  purchasableholder_subscriber.class: Heystack\Purchasable\PurchasableHolder\Subscriber
  purchasableholder.class: Heystack\Purchasable\PurchasableHolder\PurchasableHolder
  
services:

  purchasable:
    class: %purchasable.class%
    tags:
      - { name: ss_orm_backend.data_provider }

  purchasableholder_subscriber:
    class: %purchasableholder_subscriber.class%
    arguments: [@event_dispatcher, @purchasableholder, @storage]
    tags:
      - { name: event_dispatcher.subscriber }

  purchasable_input_processor:
    class: %purchasable_input_processor.class%
    arguments: [%purchasable.class%, @state, @event_dispatcher, @purchasableholder]
    tags:
      - { name: input_processor_handler.processor }
    
  purchasable_output_processor:
    class: %purchasable_output_processor.class%
    arguments: [%purchasable.class%, @state, @purchasableholder]
    tags:
      - { name: output_processor_handler.processor }

  purchasableholder:
    class: %purchasableholder.class%
    arguments: [ @state, @event_dispatcher ]
    calls:
      - [ restoreState ]
    tags:
      - { name: ss_orm_backend.data_provider }
      - { name: transaction.modifier }

  purchasable_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-purchasable/config/storage/purchasable.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
      
  purchasable_holder_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-purchasable/config/storage/purchasableholder.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
      
  transaction_purchasable_holder_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-purchasable/config/storage/transaction_purchasableholder.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
