parameters:
  product_input_processor.class: Heystack\Subsystem\Products\Product\Input\Processor
  product_output_processor.class: Heystack\Subsystem\Products\Product\Output\Processor

  productholder_subscriber.class: Heystack\Subsystem\Products\ProductHolder\Subscriber

  productholder.class: Heystack\Subsystem\Products\ProductHolder\ProductHolder

  product.class: $$$
  
services:

  product:
    class: %product.class%
    tags:
      - { name: ss_orm_backend.data_provider }

  productholder_subscriber:
    class: %productholder_subscriber.class%
    arguments: [@event_dispatcher, @productholder, @storage]
    tags:
      - { name: event_dispatcher.subscriber }

  product_input_processor:
    class: %product_input_processor.class%
    arguments: [%product.class%, @state, @event_dispatcher, @productholder]
    tags:
      - { name: input_processor_handler.processor }
    
  product_output_processor:
    class: %product_output_processor.class%
    arguments: [%product.class%, @state, @productholder]
    tags:
      - { name: output_processor_handler.processor }

  productholder:
    class: %productholder.class%
    arguments: [ @state, @event_dispatcher ]
    calls:
      - [ restoreState ]
    tags:
      - { name: ss_orm_backend.data_provider }
      - { name: transaction.modifier }

  product_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-products/config/storage/product.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
      
  product_holder_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-products/config/storage/productholder.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
      
  transaction_product_holder_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-products/config/storage/transaction_productholder.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }
