parameters:
  product_input_processor.class: Heystack\Subsystem\Products\Product\Input\Processor
  product_output_processor.class: Heystack\Subsystem\Products\Product\Output\Processor

  productholder_subscriber.class: Heystack\Subsystem\Products\ProductHolder\Subscriber

  productholder.class: Heystack\Subsystem\Products\ProductHolder\ProductHolder

  product.class: Product
  
services:


  productholder_subscriber:
    class: %productholder_subscriber.class%
    arguments: [@event_dispatcher, @productholder]

  event_dispatcher:
    class: %event_dispatcher.class%
    calls: 
      - [ addSubscriber, [ @productholder_subscriber ] ]

  product_input_processor:
    class: %product_input_processor.class%
    arguments: [%product.class%, @state, @event_dispatcher, @productholder]
    
  product_output_processor:
    class: %product_output_processor.class%
    arguments: [%product.class%, @state, @productholder]

  productholder:
    class: %productholder.class%
    arguments: [ @state, @event_dispatcher ]
    calls:
      - [ restoreState ]

  input_processor_handler:
    class: %input_processor_handler.class%
    calls:
      - [ addProcessor, [ @product_input_processor ] ]

  output_processor_handler:
    class: %output_processor_handler.class%
    calls:
      - [ addProcessor, [ @product_output_processor ] ]

  product:
    class: %product.class%

  dataobject_storage_generator:
    class: %dataobject_storage_generator.class%
    calls:
      - [ addDataObject, [ @product ] ]
      
  transaction:
    class: %transaction.class%
    calls:
      - [ addModifier, [ @productholder ] ]